-- Véhicules de démonstration (repris du prototype), à remplacer/compléter depuis l'admin
INSERT INTO vehicles (id, title, sub, type, first_reg, km, fuel, gearbox, kw, color, price, description, options_json, images_json, position) VALUES (
  'A1-21', 'Audi A1', 'Citadine — Sportback', 'citadine', '03/2021', 41000, 'Essence', 'Manuelle', 85, 'Bleu Ascari', 15900,
  'Petite citadine premium à l''entretien irréprochable, reprise avec un carnet complet et un contrôle technique tout juste réalisé.', '["Climatisation automatique","Régulateur de vitesse","Bluetooth / CarPlay","Jantes alliage 16\"","Aide au stationnement arrière","Vitres électriques","Contrôle technique OK","Carnet d''entretien complet"]', '["placeholder","placeholder","placeholder","placeholder"]', 0
);
INSERT INTO vehicles (id, title, sub, type, first_reg, km, fuel, gearbox, kw, color, price, description, options_json, images_json, position) VALUES (
  'BMW-118D', 'BMW 118d', 'Berline compacte', 'berline', '06/2020', 68000, 'Diesel', 'Automatique', 110, 'Noir Saphir', 19500,
  'Berline compacte dynamique et économique, entretenue en concession. Boîte automatique fluide, très adaptée aux trajets autoroutiers réguliers.', '["Sièges chauffants","GPS intégré","Caméra de recul","Régulateur adaptatif","Jantes alliage 17\"","Démarrage sans clé","Contrôle technique OK","Historique entretien fourni"]', '["placeholder","placeholder","placeholder","placeholder","placeholder"]', 1
);
INSERT INTO vehicles (id, title, sub, type, first_reg, km, fuel, gearbox, kw, color, price, description, options_json, images_json, position) VALUES (
  'RRE-19', 'Range Rover Evoque', 'SUV compact', 'suv', '04/2019', 72000, 'Diesel', 'Automatique', 150, 'Gris Corris', 27900,
  'SUV premium au look affirmé, parfait équilibre entre prestige et polyvalence. Vendu avec révision complète effectuée avant livraison.', '["Toit panoramique","Sièges cuir","Caméra 360°","Hayon électrique","Régulateur adaptatif","Navigation","Contrôle technique OK","Garantie disponible"]', '["placeholder","placeholder","placeholder","placeholder","placeholder"]', 2
);
INSERT INTO vehicles (id, title, sub, type, first_reg, km, fuel, gearbox, kw, color, price, description, options_json, images_json, position) VALUES (
  'GOLF-18', 'Volkswagen Golf 7', 'Compacte', 'citadine', '09/2018', 89000, 'Essence', 'Manuelle', 92, 'Blanc Pur', 13900,
  'La référence des compactes, dans un état soigné et à un kilométrage raisonnable pour l''âge du véhicule. Un excellent rapport qualité / prix.', '["Climatisation","Bluetooth","Ordinateur de bord","Jantes alliage","Aide au stationnement","Vitres électriques","Contrôle technique OK","Historique disponible"]', '["placeholder","placeholder","placeholder","placeholder"]', 3
);
INSERT INTO vehicles (id, title, sub, type, first_reg, km, fuel, gearbox, kw, color, price, description, options_json, images_json, position) VALUES (
  'CLA-180D', 'Mercedes-Benz Classe A 180d', 'Berline compacte', 'berline', '01/2020', 54000, 'Diesel', 'Automatique', 85, 'Argent Iridium', 21900,
  'Intérieur digital dernière génération, motorisation diesel sobre. Véhicule non-fumeur, deuxième main, livré avec carnet et double des clés.', '["Écran MBUX","Sièges chauffants","Caméra de recul","Régulateur adaptatif","Feux LED","CarPlay / Android Auto","Contrôle technique OK","Carnet d''entretien complet"]', '["placeholder","placeholder","placeholder","placeholder","placeholder"]', 4
);
INSERT INTO vehicles (id, title, sub, type, first_reg, km, fuel, gearbox, kw, color, price, description, options_json, images_json, position) VALUES (
  '2008-21', 'Peugeot 2008', 'SUV compact', 'suv', '05/2021', 38000, 'Essence', 'Manuelle', 96, 'Rouge Ultimate', 17500,
  'SUV compact récent et peu kilométré, garantie constructeur encore active sur certains organes. Look moderne, i-Cockpit digital.', '["i-Cockpit digital","Caméra de recul","Régulateur adaptatif","CarPlay / Android Auto","Jantes alliage 17\"","Feux LED","Contrôle technique OK","Garantie restante"]', '["placeholder","placeholder","placeholder","placeholder"]', 5
);

-- Avis clients (73 avis réels, importés depuis AutoScout24)
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('peter gautier', '01.02.2026', 5, 'Une personne honnête et la voiture est parfaitement conforme à la description. Transaction fluide et correcte.', 0, 0);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Aurélie', '11.11.2025', 5, 'Très contente de mon achat effectué chez JNN. Personne très compétente, et répond assez vite à vos demandes.', 0, 1);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('S Rudra', '29.10.2025', 5, 'Jabir is a good seller who showed me the car and help me. He is to be trusted because he knows his job very well.', 0, 2);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Delhez L', '28.10.2025', 5, 'Professionnalisme / proactivité / accessibilité.', 0, 3);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Isabelle', '10.09.2025', 5, 'Au départ un peu sceptique, mais après quelques minutes de discussion avec Edan, le courant est très bien passé. Il ne force pas à la vente, répond sans détour à nos questions. La voiture nous a été livrée dans un état impeccable, encore plus belle que la première fois.', 1, 4);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('MEGALI Gauthier', '30.06.2025', 5, 'Très satisfait de notre achat ! Le véhicule est conforme à l''annonce, en excellent état. Le vendeur a été très sympa, disponible et transparent tout au long du processus.', 1, 5);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Selin', '12.04.2025', 5, 'We zijn zeer tevreden met onze aankoop bij deze verkoper. Hij was vriendelijk, gaf genoeg en gepaste uitleg. We raden deze verkoper zeker aan!', 0, 6);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Amelot', '21.02.2025', 5, 'Edan le patron est top, arrangeant, pro, n''hésite pas à vous appeler. Je connaissais des soucis pour rapatrier la voiture en France, il m''a proposé plein de solutions.', 0, 7);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('L.Z', '06.09.2023', 5, 'Vendeur disponible et très professionnel. A recommander !', 0, 8);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Romane', '04.09.2023', 5, 'Compétent, disponible, serviable et répond très vite par message et téléphone donc le contact est très facile. Je recommande.', 0, 9);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('joshuanyame', '10.08.2023', 5, 'Thanks, you did well for me, on my dealing with you.', 0, 10);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Anass Lmarz', '09.06.2023', 5, 'Le service client était excellent, le personnel professionnel et compétent. Je n''hésiterai pas à revenir pour mes futurs besoins.', 0, 11);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Changervraiment', '11.05.2023', 5, 'Edan s''est révélé fiable, gentil, disponible et à l''écoute. Il connaît bien le fonctionnement des véhicules qu''il présente. On sent quelqu''un qui vit son activité avec le cœur.', 0, 12);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Scale', '03.04.2023', 4, 'Personne très aimable, très correcte, très commerciale et de bons conseils. Je recommande.', 1, 13);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Philippe Le Jeune', '16.03.2023', 5, 'Top top.', 0, 14);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Jipeg', '07.02.2023', 5, 'Très bon contact, vendeur réactif et à l''écoute, les véhicules sont récents, très propres et conformes aux annonces. À recommander !', 0, 15);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Geert', '28.12.2022', 5, 'Véhicule acheté en parfait état, prix correct, vendeur attentif qui répond vite à toutes les questions. Un achat d''occasion comporte toujours un risque, mais j''ai eu un bon feeling dès le premier contact.', 1, 16);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Belinda G.', '27.12.2022', 5, 'Super vendeur ! Bien documenté sur ses véhicules. J''ai eu 4 nouveaux pneus, les disques, les plaquettes, les tapis et le polish du phare offerts. Il est ponctuel et respecte ses engagements.', 1, 17);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Aurore', '24.12.2022', 5, 'Un vendeur à l''écoute et professionnel, proposant des véhicules différents et pour toutes les bourses. Patient avec moi, je ne regrette pas mon achat pour ma toute première voiture.', 0, 18);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('AC COCO', '17.12.2022', 5, 'Très bon service et sérieux.', 0, 19);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Vdk', '16.12.2022', 5, 'Zeer vriendelijke en professioneel!', 0, 20);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Nico', '12.12.2022', 5, 'Content de mon achat, aucun problème sur le véhicule, vendeur dispo et honnête.', 0, 21);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Greg bmw 118d', '06.12.2022', 5, 'Vendeur investi, très professionnel. Fait son maximum pour trouver une date de rdv qui arrange tout le monde.', 0, 22);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Samuel', '17.11.2022', 5, 'Transaction rapide.', 0, 23);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Bart', '03.11.2022', 5, 'Correcte, rapide et agréable transaction. À conseiller.', 0, 24);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Sophie', '28.10.2022', 5, 'Très contente du service, bonne voiture à recommander pour achat et aussi pour la vente, très sérieux.', 0, 25);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Odilon', '28.10.2022', 5, 'Nous sommes ravis de notre achat. Vendeur très réactif, disponible, pro, sympathique. Nous recommandons vivement Edan !', 0, 26);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Pire', '09.07.2022', 5, 'Heel tevreden en heel vriendelijk. Goede uitleg over alles en alles tip top in orde.', 0, 27);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Bi', '02.07.2022', 5, 'Edan est très attentif au besoin du client. Bienveillant et sérieux. Je recommande vivement cette adresse.', 0, 28);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('seb', '29.06.2022', 5, 'Très professionnel et disponible, la vente s''est déroulée parfaitement. Il répond à toutes vos questions pour vous rassurer. Je recommande fortement !', 0, 29);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Fafa', '22.06.2022', 5, 'Très professionnel, surtout la ponctualité et la confiance. Service impeccable, merci.', 0, 30);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Adriana', '18.06.2022', 5, 'Personne très disponible (jour/heure) et sympathique qui répond aux demandes du client lors de la vente. Il a rapidement remis la voiture en état, fait le contrôle technique et nettoyé le véhicule.', 0, 31);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Hanna Ben - Declercq', '13.06.2022', 5, 'Zeer tevreden! Vlotte verkoop. Keuring op tijd, vriendelijke jongeman. De verkoper kent zijn vak! Super content met mijn nieuw autootje.', 0, 32);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Momo', '01.06.2022', 5, 'Professionnel, aimable, à l''écoute de son client et un service parfait. Je recommande à tous, encore merci pour sa disponibilité et sa confiance.', 0, 33);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Taiysha Mathoera', '26.05.2022', 5, 'Een hele vriendelijke man! Goeie service.', 0, 34);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Ben', '19.05.2022', 5, 'Méfiant au début car première fois que j''achète à ce prix, très disponible et fiable. La vente et la possession du véhicule n''a duré que 3 jours. Je recommande.', 1, 35);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Julien', '18.05.2022', 5, 'J''ai eu un rendez-vous le jour même, deux heures après l''appel. Le jour de la réception, je n''avais pas de possibilité de venir : il a proposé de venir me chercher à mon domicile. Très rare chez un vendeur, je recommande.', 1, 36);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Papou', '04.05.2022', 5, 'Très bon service, il s''est débrouillé pour passer très rapidement la voiture au contrôle technique. Merci.', 0, 37);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Amelie', '01.05.2022', 5, 'A été très disponible et très fiable, donne tous les conseils nécessaires sur les véhicules désirés.', 0, 38);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Cassandrai', '29.04.2022', 5, 'Nickel ! Disponible et rapide ! Je recommande ce vendeur.', 0, 39);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Ali', '23.04.2022', 5, 'Client satisfait.', 0, 40);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Ambre', '21.04.2022', 5, 'Personne très à l''écoute et plus qu''à recommander ! Tout était parfait.', 0, 41);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('David', '21.04.2022', 5, 'Prima en correcte service.', 0, 42);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Alexandra', '18.04.2022', 5, 'J''ai reçu un très bon prix pour ma voiture, c''est le seul marchand ayant donné autant. Contente du nouvel achat. Très bon service après-vente aussi. Je recommande !', 0, 43);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Yasmina', '14.04.2022', 5, 'Tout était top ! Merci encore.', 0, 44);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Garance', '06.04.2022', 5, 'Étant acheteuse française, j''étais inquiète sur les démarches administratives, mais tout a été fait dans les règles — il a même refait le contrôle technique belge pour nous rassurer. Garçon très sympathique.', 1, 45);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Benoit holemans', '27.03.2022', 5, 'J''ai acheté cette voiture sur annonce, par téléphone, sans même être allé la voir sur place. Le vendeur m''a certifié que tout était en règle. Tout était ok à la récupération. Je recommande.', 0, 46);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Stéphanie', '27.03.2022', 5, 'Vendeur arrangeant et disponible. Je recommande fortement !', 0, 47);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Theodhor', '05.03.2022', 5, 'The communication was great and everything about the car was the same as described. Totally recommend this seller!!', 0, 48);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Hamza Sebbah', '25.02.2022', 5, 'Fiable et très disponible !', 0, 49);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Cedric', '25.02.2022', 5, 'Très bon service et sérieux.', 0, 50);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Denis', '13.02.2022', 5, 'Très content.', 0, 51);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Ben', '09.02.2022', 5, 'Really happy with my new Range Rover Evoque! If I buy another car in the future, I will go back. It''s a seller I can trust with my eyes closed! All 5 stars are deserved.', 1, 52);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Adrianvreux', '22.01.2022', 5, 'Très bien. Aucun défaut à signaler.', 0, 53);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Katrien', '22.01.2022', 5, 'Très bien !', 0, 54);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Denzel', '22.01.2022', 5, 'Sérieux, honnête et très pro. Je recommande sans hésitation.', 0, 55);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Rajah', '28.12.2021', 5, 'Je ne m''y connaissais pas du tout en achat de voiture. Le vendeur a été très à l''écoute de ce que je recherchais, très professionnel malgré mes exigences. Si je devais changer de voiture, je sais que je retournerai là !', 0, 56);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Dreum', '20.12.2021', 5, 'Bonne présentation du véhicule et respect des délais pour la livraison.', 0, 57);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Manon Bovenisty', '17.12.2021', 5, 'Très satisfaite, rapidité, professionnalisme, bon achat !', 0, 58);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Jerem', '02.12.2021', 5, 'Rien à dire. Visite du véhicule le mardi, et le mardi suivant le véhicule était prêt.', 0, 59);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Hugo T', '01.12.2021', 5, 'Très content de mon achat. Aucune mauvaise surprise, véhicule acheté à distance. Vendeur très professionnel, très réactif. Je recommande vivement.', 0, 60);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Simon', '30.11.2021', 5, 'Très bon vendeur, que des belles voitures, prix du marché. Merci à Jabir pour son écoute et sa disponibilité. Je le recommande.', 0, 61);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Mia', '13.11.2021', 5, 'Vendeur très gentil, à l''écoute et très professionnel. Une personne de confiance !', 0, 62);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Thibaut', '10.11.2021', 5, 'Vraiment professionnel, à l''écoute du client et disponible ! Je recommande !', 0, 63);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('victor', '05.11.2021', 5, 'Parfait, super pro.', 0, 64);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Brieuc', '05.11.2021', 5, 'Rien à dire.', 0, 65);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Michail', '28.10.2021', 5, 'Véhicule en parfait état. Fiabilité et confiance du vendeur. Je recommande à 100% et je n''hésiterais pas à retravailler avec lui.', 0, 66);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Anass', '27.10.2021', 5, 'Ravie de l''accueil reçu lorsque nous nous sommes rendus au garage. J''ai pu avoir mon véhicule rapidement sans aucun problème. Vendeur très professionnel !', 0, 67);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Manon', '10.10.2021', 5, 'Super achat, j''en suis ravie. Merci beaucoup.', 0, 68);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Muhammed bulduk', '05.10.2021', 5, 'Vriendelijk, correct en snel. Alle nodige documenten en uitleg waren aanwezig vanaf minuut 1. Nog nooit zo snel een kwalitatief wagen aangekocht. Zeker een aanrader!', 0, 69);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Guy', '27.09.2021', 5, 'Vente très correcte. J''étais satisfait. Tout s''est déroulé sans problèmes.', 0, 70);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Antoine60', '02.08.2021', 5, 'Bon relationnel, bon véhicule, flexibilité des horaires, de bon conseil, professionnel. Je recommande !', 0, 71);
INSERT INTO reviews (author, review_date, stars, body, is_featured, position) VALUES ('Estelle', '02.08.2021', 5, 'Tout s''est très bien passé pour cet achat. La voiture correspondait bien à la description, le véhicule était en très bon état et nous avons pu l''essayer. Vendeur très correct, honnête et sympathique.', 0, 72);
